### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by isaac-yoon** [isaac-yoon/DisArray#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [ ] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
- [x] splash images should be centered to the page
    * This might just be because of different window size that I'm looking at it on.

The session buttons look pretty big. I'd recommend the following changes:
- [ ] have just the login button on the splash page.
    - [ ] This button should be styled the same way as Discord's
- [x] When the login button is clicked, this should show the user a page that looks like this one: https://discordapp.com/login
          * You dont need the animation stuff in the top left, or the QR code stuff. But the form should look like the one in that link.
          * You can accomplish this with a modal or utilizing react router. I'll let you decide how you want to do it
- [x] The login page should have a demo login button that will fill the form out for the user and then submit it. 
- [x] The login page should have a link/button that will take the user to the sign up page.

Let me know if you have any questions.

**Comment by isaac-yoon** [comment]
I sort of want to keep the three buttons. I'm so attached to my modals...
